services:
  # --- SERVIÇO DE ESTOQUE ---
  stock-service:
    build:
      context: ./stock-service     
      dockerfile: Dockerfile       
    container_name: stock-service
    ports:
      - "8088:8088"                
    # ADICIONE ESTE BLOCO ENVIRONMENT:
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/stock_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=***REMOVED***
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - distributed-network        
    depends_on:
      - postgres                   
      - kafka                      

  # --- SERVIÇO DE ORDENS ---
  order-service:
    build:
      context: ./order-service    
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8080:8080"
    # ADICIONE ESTE BLOCO ENVIRONMENT (Ajuste a URL se ele usar outro banco no futuro):
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/stock_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=***REMOVED***
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - distributed-network
    depends_on:
      - kafka

  # --- BANCO DE DADOS (POSTGRESQL) ---
  postgres:
    image: postgres:16
    container_name: stock_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stock_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ***REMOVED***
    networks:
      - distributed-network

  # --- MENSAGERIA (KAFKA) ---
  kafka:
    image: apache/kafka:latest     
    container_name: kafka_container
    ports:
      - "9092:9092"
    networks:
      - distributed-network

# --- CRIAÇÃO DA REDE PRINCIPAL QUE ABRAÇA O PROJETO ---
networks:
  distributed-network:
    driver: bridge
