version: '3.8'

services:
  # --- BANCO DO CLIENT-SERVICE ---
  db-client:
    image: postgres:16
    container_name: pg-client
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: ***REMOVED***
      POSTGRES_DB: client_db
    ports:
      - "5439:5432" # Acessível na sua máquina via localhost:5432
    volumes:
      - ./v_client_db:/var/lib/postgresql/data # <- ADICIONE ESTA LINHA EXATAMENTE AQUI

  # --- BANCO DO ORDER-SERVICE ---
  db-order:
    image: postgres:16
    container_name: pg-order
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ***REMOVED***
      POSTGRES_DB: order_db
    ports:
      - "5442:5432" # Porta externa exclusiva 5442
    volumes:
      - ./v_order_db:/var/lib/postgresql/data # Pasta física exclusiva

  # --- BANCO DO STOCK-SERVICE ---
  db-stock:
    image: postgres:16
    container_name: pg-stock
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ***REMOVED***
      POSTGRES_DB: stock_db
    ports:
      - "5443:5432" # Porta externa exclusiva 5443
    volumes:
      - ./v_stock_db:/var/lib/postgresql/data # Pasta física exclusiva
