server.port=8081
spring.application.name=client-service

# Aponta para o serviço 'db-client' na porta padrão interna
spring.datasource.url=jdbc:postgresql://distributed-postgres:5432/client_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
management.endpoints.web.exposure.include=health,info
