apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: meu-sistema-distribuido
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service-container
          image: seu-usuario-dockerhub/notification-service:latest
          ports:
            - containerPort: 8086
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: meu-sistema-distribuido
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
